CODE SEGMENT
	ASSUME CS:CODE
START:
	MOV AL,80H       
	MOV DX,0686H
	OUT DX,AL
LL3:	MOV AL,00H        ;随便什么值
	MOV DX,0640H
	OUT DX,AL             ;做启动信号
	MOV CX,0FFH
LL1:    MOV BX,0FFH
LL2:    DEC BX
	JNZ LL2
	LOOP LL1
	MOV DX,0640H
	IN  AL,DX
	MOV DX,0683H
	OUT DX,AL
	JMP LL3	
	MOV AH,4CH
	INT 21H
CODE ENDS
END START
